/**
 * @file This file contains constants used throughout the application,
 * including API configurations, static data, and translation strings.
 */

// The base URL for the WorldTimeAPI used to fetch time data.
export const API_BASE_URL = 'https://worldtimeapi.org/api';

// A collection of inspirational quotes about time to be displayed in the footer.
export const QUOTES = [
    { text: "Time is your scarce capital; spend it on what matters most.", author: "Steve Jobs" },
    { text: "Do tomorrow's tasks today; do today's tasks now, without delay.", author: "Colonel Nurun Nabi" },
    { text: "Don't waste time; perfection often hides in procrastination.", author: "Ratan Tata" },
    { text: "Minutes define destiny more than intentions ever will.", author: "Michael Jackson" },
    { text: "Act now; hesitation steals life's best opportunities.", author: "Marcus Aurelius" },
    { text: "Time teaches, if you are willing to learn daily.", author: "Seneca" },
    { text: "Time heals, but wasted time wounds future possibilities.", author: "Epictetus" },
    { text: "Every moment invested compounds into future advantage.", author: "Ryan Holiday" },
    { text: "Time is honest; it reveals our true priorities.", author: "Marcus Aurelius" },
    { text: "Live deliberately; let time reward your choices.", author: "Al-Ghazali" },
    { text: "Time is the truest measure of commitment.", author: "Ibn Sina (Avicenna)" },
    { text: "Use time to build, not merely to plan.", author: "Rumi" },
    { text: "Plan quickly, act faster, reflect faster still.", author: "Imam Ali" },
    { text: "Time waits for no one; move with urgency.", author: "Allama Iqbal" },
    { text: "Value minutes; they become years before you notice.", author: "Ibn Rushd (Averroes)" },
    { text: "Time is the raw material of achievement.", author: "Ibn Khaldun" },
    { text: "Guard your time; others will gladly consume it.", author: "Al-Farabi" },
    { text: "Time punishes the idle, favors the persistent.", author: "Al-Biruni" },
    { text: "Time builds habits that shape entire lifetimes.", author: "Benjamin Franklin" },
    { text: "Waste a minute, lose the rhythm for days.", author: "William Shakespeare" },
    { text: "Time is honest; it rewards steady, small effort.", author: "Albert Einstein" },
    { text: "Don't delay; the future needs what you build today.", author: "Leonardo da Vinci" },
    { text: "Time rewards clarity, not endless rumination.", author: "Mahatma Gandhi" },
    { text: "Use time to serve, not merely to impress.", author: "Nelson Mandela" },
    { text: "Invest time in people who grow alongside you.", author: "Oprah Winfrey" },
    { text: "Time multiplies when you focus on essential work.", author: "Bill Gates" },
    { text: "Respect time; it sculpts ordinary efforts into excellence.", author: "Elon Musk" },
    { text: "Short daily work beats sporadic grand gestures.", author: "Mark Twain" },
    { text: "Time is precious; guard it from trivial demands.", author: "Winston Churchill" },
    { text: "Every minute counts toward freedom from regret.", author: "Abraham Lincoln" },
    { text: "Small daily disciplines yield huge time dividends.", author: "Confucius" },
    { text: "Time is the quiet ally of persistent purpose.", author: "Lao Tzu" },
    { text: "Time turns intention into either results or regret.", author: "Buddha" },
    { text: "Measure life by moments used, not hours wasted.", author: "Socrates" },
    { text: "Time spent learning returns lifelong dividends.", author: "Plato" },
    { text: "Time made discipline into genius through repetition.", author: "Aristotle" },
    { text: "Act now; success favors prompt, bold action.", author: "Ratan Tata" },
    { text: "Time rewards those who keep improving, always.", author: "Steve Wozniak" },
    { text: "Procrastination multiplies tasks; start now to shrink them.", author: "Mother Teresa" },
    { text: "Time forgives effort but not prolonged neglect.", author: "John F. Kennedy" },
    { text: "Time is the canvas where habits paint outcomes.", author: "Margaret Thatcher" },
    { text: "Value time more than fleeting social applause.", author: "Dalai Lama" },
    { text: "Make minutes count; they build your legacy.", author: "Martin Luther King Jr." },
    { text: "Time shows character; daily actions reveal truth.", author: "Victor Hugo" },
    { text: "Time's treasure: small, steady improvements compounded.", author: "Pablo Picasso" },
    { text: "Time rewards those who take consistent tiny steps.", author: "Charlie Chaplin" },
    { text: "Don't postpone excellence; practice it every single day.", author: "Stephen King" },
    { text: "Time is the only equalizer of possibility.", author: "J.K. Rowling" },
    { text: "Use today's time to create tomorrow's opportunities.", author: "Malala Yousafzai" },
    { text: "Time is the adviser that speaks through results.", author: "Ibn Taymiyyah" },
    { text: "Minutes create momentum; momentum creates breakthroughs.", author: "Imam Bukhari" },
    { text: "Time demands action; wisdom follows from doing.", author: "Ibn Majah" },
    { text: "Spend time learning more than showing off.", author: "Yusuf Islam (Cat Stevens)" },
    { text: "Time rewards humility paired with relentless effort.", author: "Imam Malik" },
    { text: "Preserve time for what matures into meaning.", author: "Imam Shafi'i" },
    { text: "Time is strict; use it with wise intention.", author: "Ibn Hazm" },
    { text: "Time refines character through repeated small choices.", author: "Sadi of Shiraz" },
    { text: "Act now; future success grows from today's tasks.", author: "Hafez" },
    { text: "Minutes saved today are milestones tomorrow.", author: "Anas ibn Malik" },
    { text: "Time exposes truth; live in alignment daily.", author: "Aisha bint Abu Bakr" },
    { text: "Time reveals leadership by persistent, steady deeds.", author: "Umar ibn al-Khattab" },
    { text: "Spend time shaping values, not only outcomes.", author: "Ali ibn Abi Talib" },
    { text: "Time is a lens focusing consistent daily practice.", author: "Rabindranath Tagore" },
    { text: "Time rewards those who convert ideas into action.", author: "John Locke" },
    { text: "Every minute matters; use it for meaningful pursuit.", author: "Niccolò Machiavelli" },
    { text: "Time is strategy's most unforgiving opponent; act.", author: "Sun Tzu" },
    { text: "Time magnifies choices; choose long-term value.", author: "Genghis Khan" },
    { text: "Time measures the worth of every small effort.", author: "Pliny the Elder" },
    { text: "Time shapes knowledge into usable wisdom through repetition.", author: "Euclid" },
    { text: "Time demands experiments; learn fast, iterate faster.", author: "Galileo Galilei" },
    { text: "Treasure time; it's rarer than gold.", author: "Nicolaus Copernicus" },
    { text: "Time rewards curiosity executed with steady work.", author: "Stephen Hawking" },
    { text: "Time is a resource; manage it like capital.", author: "Tim Cook" },
    { text: "Protect your time from needless urgency and noise.", author: "Sheryl Sandberg" },
    { text: "Focus time on leverage, not on busywork.", author: "Larry Page" },
    { text: "Time grows impact when you prioritize ruthlessly.", author: "Sergey Brin" },
    { text: "Time values products that solve real human problems.", author: "Sundar Pichai" },
    { text: "Work with urgency; time doesn't promise tomorrow.", author: "Richard Branson" },
    { text: "Time appreciates disciplined routines more than occasional genius.", author: "Jack Ma" },
    { text: "Use time to build systems, not only tasks.", author: "Howard Schultz" },
    { text: "Time spent well grants freedom later.", author: "Frederick Douglass" },
    { text: "Time is a teacher; heed its daily lessons.", author: "Simone de Beauvoir" },
    { text: "Value time above convenience for lasting success.", author: "Eleanor Roosevelt" },
    { text: "Time reveals courage; small brave acts add up.", author: "Brene Brown" },
    { text: "Time rewards leadership that serves, not merely speaks.", author: "Angela Merkel" },
    { text: "Time is a mirror reflecting what you prioritize.", author: "Stephen Covey" },
    { text: "Every minute is proof of your chosen priorities.", author: "Peter Drucker" },
    { text: "Time multiplies mastery for patient practitioners.", author: "Ibn al-Nafis" },
    { text: "Time is methodical; show up, day after day.", author: "Al-Kindi" },
    { text: "Use each moment to perfect your craft.", author: "Ibn al-Haytham" },
    { text: "Time turns curiosity into competence through practice.", author: "Ralph Waldo Emerson" },
    { text: "Time's patience builds mountains from daily footsteps.", author: "Henry David Thoreau" },
    { text: "Time is kind to humble, consistent effort.", author: "Khalil Gibran" },
    { text: "Turn minutes into meaning; act with purpose now.", author: "Dante Alighieri" },
    { text: "Time is relentless; choose commitments you can keep.", author: "Thomas Edison" },
    { text: "Time is a stern coach; listen and improve.", author: "Samuel Johnson" },
    { text: "Don't waste time polishing illusions; build real value.", author: "George Eliot" },
    { text: "Time is brief; make your actions unmistakably meaningful.", author: "Emily Dickinson" },
    { text: "Time forgives mistakes more easily than wasted years.", author: "Edgar Allan Poe" },
    { text: "Let time reward the work you quietly do.", author: "John Milton" },
    { text: "Time is the measuring stick of silent progress.", author: "Steve Jobs" },
    { text: "Time punishes delay; start even imperfectly today.", author: "Colonel Nurun Nabi" },
    { text: "Act swiftly; delay amplifies uncertainty and loss.", author: "Ratan Tata" },
    { text: "Time is finite; invest it in meaningful creation.", author: "Michael Jackson" },
    { text: "Time rewards those who simplify and execute consistently.", author: "Marcus Aurelius" },
    { text: "Cultivate small wins; time will compound them cleverly.", author: "Seneca" },
    { text: "Time demands focus; scattered attention yields little.", author: "Epictetus" },
    { text: "Start now; perfection is the enemy of progress.", author: "Ryan Holiday" },
    { text: "Time clarifies purpose when you pursue it daily.", author: "Marcus Aurelius" },
    { text: "Minutes of effort beat hours of idle dreaming.", author: "Al-Ghazali" },
    { text: "Time is tiny steps toward monumental change.", author: "Ibn Sina (Avicenna)" },
    { text: "Spend mornings on creating, evenings on learning more.", author: "Rumi" },
    { text: "Time appreciates decisive action over hesitant planning.", author: "Imam Ali" },
    { text: "Time spent wisely creates freedom for future choices.", author: "Allama Iqbal" },
    { text: "Time is a compass directing purposeful lives.", author: "Ibn Rushd (Averroes)" },
    { text: "Time reveals priorities by what you consistently choose.", author: "Ibn Khaldun" },
    { text: "Time rewards disciplined builders, not fleeting performers.", author: "Al-Farabi" },
    { text: "Time is a teacher of stubborn persistence.", author: "Al-Biruni" },
    { text: "Use time to craft habits, then guard them.", author: "Benjamin Franklin" },
    { text: "Today shapes tomorrow; use time with intention.", author: "William Shakespeare" },
    { text: "Time is counted value; spend it on creation.", author: "Albert Einstein" },
    { text: "Time respects those who show up, day after day.", author: "Leonardo da Vinci" },
    { text: "Minutes used wisely make regrets steadily vanish.", author: "Mahatma Gandhi" },
    { text: "Time builds character through repeated small decisions.", author: "Nelson Mandela" },
    { text: "Time earns trust through consistent, honest work.", author: "Oprah Winfrey" },
    { text: "Time is limited; choose depth over endless breadth.", author: "Bill Gates" },
    { text: "Time magnifies the brave who persist through adversity.", author: "Elon Musk" },
    { text: "Time is the raw material of rare craftsmanship.", author: "Mark Twain" },
    { text: "Don't borrow tomorrow's time for today's comfort.", author: "Winston Churchill" },
    { text: "Time is the stage where effort becomes legend.", author: "Abraham Lincoln" },
    { text: "Time reveals wisdom that impatience never finds.", author: "Confucius" },
    { text: "Use time to move toward the life you want.", author: "Lao Tzu" },
    { text: "Time turns repeated practice into effortless skill.", author: "Buddha" },
    { text: "Time values honest labour above clever shortcuts.", author: "Socrates" },
    { text: "Time is a mirror: your habits reflect back.", author: "Plato" },
    { text: "Time is the teacher that rewards steady curiosity.", author: "Aristotle" },
    { text: "Act now; let time validate your commitment.", author: "Ratan Tata" },
    { text: "Time is earned through small disciplined daily acts.", author: "Steve Wozniak" },
    { text: "Time is the margin between chaos and achievement.", author: "Mother Teresa" },
    { text: "Time is the currency of responsibility; spend wisely.", author: "John F. Kennedy" },
    { text: "Use time to answer questions, not to avoid them.", author: "Margaret Thatcher" },
    { text: "Time is finite; spend it on what elevates others.", author: "Dalai Lama" },
    { text: "Minutes invested in learning beat months wasted in doubt.", author: "Martin Luther King Jr." },
    { text: "Time cleanses distractions; focus refines purpose.", author: "Victor Hugo" },
    { text: "Time makes ordinary practice produce extraordinary skill.", author: "Pablo Picasso" },
    { text: "Time will reward the humble daily worker.", author: "Charlie Chaplin" },
    { text: "Act now and let time handle results.", author: "Stephen King" },
    { text: "Time is silent; its results speak volumes later.", author: "J.K. Rowling" },
    { text: "Time rewards courage; hesitance steals tomorrow's chances.", author: "Malala Yousafzai" },
    { text: "Time values truth; speak and act accordingly.", author: "Ibn Taymiyyah" },
    { text: "Minutes of practice outvalue a thousand empty plans.", author: "Imam Bukhari" },
    { text: "Time favors those who convert prayer into action.", author: "Ibn Majah" },
    { text: "Shape time with learning, service, and steady effort.", author: "Yusuf Islam (Cat Stevens)" },
    { text: "Time is the messenger of consistent devotion.", author: "Imam Malik" },
    { text: "Time is honest; it returns what you consistently sow.", author: "Imam Shafi'i" },
    { text: "Use time to create knowledge, not only to display it.", author: "Ibn Hazm" },
    { text: "Time is a test: persist and you'll be refined.", author: "Sadi of Shiraz" },
    { text: "Time rewards the patient craftsman more than the quick show.", author: "Hafez" },
    { text: "Time is built from minutes of focused intention.", author: "Anas ibn Malik" },
    { text: "Invest time in truth; it repays with clarity.", author: "Aisha bint Abu Bakr" },
    { text: "Time is a mirror; your priorities show plainly.", author: "Umar ibn al-Khattab" },
    { text: "Time rewards courage to act despite fear.", author: "Ali ibn Abi Talib" },
    { text: "Time grows wisdom for those who steadily seek it.", author: "Rabindranath Tagore" },
    { text: "Time is invested where commitment meets careful planning.", author: "John Locke" },
    { text: "Time is brief; align it with your deepest aim.", author: "Niccolò Machiavelli" },
    { text: "Time is strategic; use it to shape outcomes.", author: "Sun Tzu" },
    { text: "Time is relentless; build habits that survive it.", author: "Genghis Khan" },
    { text: "Time silently crowns the persistent and forgets the rest.", author: "Pliny the Elder" },
    { text: "Time chisels talent into enduring mastery.", author: "Euclid" },
    { text: "Time rewards those who test ideas early and often.", author: "Galileo Galilei" },
    { text: "Time respects those who create patiently, steadily.", author: "Nicolaus Copernicus" },
    { text: "Time is the laboratory for audacious experiments.", author: "Stephen Hawking" },
    { text: "Guard your time like your most precious asset.", author: "Tim Cook" },
    { text: "Time is earned through discipline more than desire.", author: "Sheryl Sandberg" },
    { text: "Time multiplies when you harness collective focus.", author: "Larry Page" },
    { text: "Time demands meaningful questions more than instant answers.", author: "Sergey Brin" },
    { text: "Protect time from the trivial; nurture depth.", author: "Sundar Pichai" },
    { text: "Time is generous to those who show up daily.", author: "Richard Branson" },
    { text: "Time rewards those who turn scarcity into creativity.", author: "Jack Ma" },
    { text: "Spend time on systems that amplify your efforts.", author: "Howard Schultz" },
    { text: "Time converts tiny improvements into undeniable mastery.", author: "Frederick Douglass" },
    { text: "Time reveals what courage looks like in practice.", author: "Simone de Beauvoir" },
    { text: "Invest time where your heart and talent meet.", author: "Eleanor Roosevelt" },
    { text: "Time reveals what you truly choose to protect.", author: "Brene Brown" },
    { text: "Time teaches leadership by consistent, humble service.", author: "Angela Merkel" },
    { text: "Time respects those who plan but act faster.", author: "Stephen Covey" },
    { text: "Spend time on what moves outcomes forward.", author: "Peter Drucker" },
    { text: "Time is the currency of thoughtful, steady improvement.", author: "Ibn al-Nafis" },
    { text: "Use time to experiment, refine, then scale.", author: "Al-Kindi" },
    { text: "Time is the patient architect of understanding.", author: "Ibn al-Haytham" },
    { text: "Time rewards those who convert failure into lessons.", author: "Ralph Waldo Emerson" },
    { text: "Use time to mature ideas into tested truths.", author: "Henry David Thoreau" },
    { text: "Time values subtle improvements more than grand promises.", author: "Khalil Gibran" },
    { text: "Be faithful with minutes; time will reward you.", author: "Dante Alighieri" },
    { text: "Time is limited; pick commitments you can keep.", author: "Thomas Edison" },
    { text: "Time grows mastery through humble repeated practice.", author: "Samuel Johnson" },
    { text: "Spend time where value compounds, not where it dilutes.", author: "George Eliot" },
    { text: "Time is honest; it measures what truly matters.", author: "Emily Dickinson" },
    { text: "Time rewards courage shown consistently, not occasionally.", author: "Edgar Allan Poe" },
    { text: "Time is the patient architect of lasting achievement.", author: "John Milton" },
    { text: "Time rewards early starters who persist through setbacks.", author: "Steve Jobs" },
    { text: "Do not delay: start imperfectly, finish remarkably.", author: "Colonel Nurun Nabi" },
    { text: "Time favors those who clear distractions, then create.", author: "Ratan Tata" },
    { text: "Use minutes to create rather than to consume endlessly.", author: "Michael Jackson" },
    { text: "Time is truth's ally; results will reveal sincerity.", author: "Marcus Aurelius" },
    { text: "Keep time sacred; it shapes the soul's daily work.", author: "Seneca" },
    { text: "Time composes greatness from many small consistent acts.", author: "Epictetus" },
    { text: "Time is earned by work, not by intention.", author: "Ryan Holiday" },
    { text: "Time forgives hustle more than endless planning.", author: "Marcus Aurelius" },
    { text: "Use time to master the craft you love.", author: "Al-Ghazali" },
    { text: "Minutes of discipline outweigh months of empty dreaming.", author: "Ibn Sina (Avicenna)" },
    { text: "Time rewards focus applied to essential tasks.", author: "Rumi" },
    { text: "Time is the greatest teacher of real priorities.", author: "Imam Ali" },
    { text: "Value time; it's the true measure of freedom.", author: "Allama Iqbal" },
    { text: "Time is the home of steady, meaningful effort.", author: "Ibn Rushd (Averroes)" },
    { text: "Time punishes wasted promise, rewards fulfilled effort.", author: "Ibn Khaldun" },
    { text: "Time is the forge of patient excellence.", author: "Al-Farabi" },
    { text: "Use time to learn; knowledge compounds across years.", author: "Al-Biruni" },
    { text: "Time prefers perseverance to occasional brilliance.", author: "Benjamin Franklin" },
    { text: "Time organizes life; design your hours intentionally.", author: "William Shakespeare" },
    { text: "Time sharpens curiosity into applied discovery.", author: "Albert Einstein" },
    { text: "Time demands creating more than merely consuming.", author: "Leonardo da Vinci" },
    { text: "Spend time on what your future self will thank.", author: "Mahatma Gandhi" },
    { text: "Time turns small kindnesses into lasting reputations.", author: "Nelson Mandela" },
    { text: "Guard time fiercely; squander none on empty praise.", author: "Oprah Winfrey" },
    { text: "Time is the test of all meaningful work.", author: "Bill Gates" },
    { text: "Use time to build strengths, not excuses.", author: "Elon Musk" },
    { text: "Time rewards those who pursue mastery patiently.", author: "Mark Twain" },
    { text: "Time is brief; act like it is precious.", author: "Winston Churchill" },
    { text: "Time shapes history through repeated humble actions.", author: "Abraham Lincoln" },
    { text: "Time reveals the outcome of consistent moral choices.", author: "Confucius" },
    { text: "Time multiplies meaning when paired with simplicity.", author: "Lao Tzu" },
    { text: "Time is the potter shaping disciplined living.", author: "Buddha" },
    { text: "Use time to question, then to act.", author: "Socrates" },
    { text: "Time is the apprenticeship of becoming wise.", author: "Plato" },
    { text: "Time honors repeated craftsmanship over fleeting brilliance.", author: "Pliny the Elder" },
];

// A curated list of cities with their corresponding timezone data.
// This is used for search suggestions and enriching the data from the time API.
export const CITY_DATA = [
    { name: "New York", country: "USA", timezone: "America/New_York", flag: "🇺🇸" },
    { name: "London", country: "United Kingdom", timezone: "Europe/London", flag: "🇬🇧" },
    { name: "Tokyo", country: "Japan", timezone: "Asia/Tokyo", flag: "🇯🇵" },
    { name: "Paris", country: "France", timezone: "Europe/Paris", flag: "🇫🇷" },
    { name: "Sydney", country: "Australia", timezone: "Australia/Sydney", flag: "🇦🇺" },
    { name: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka", flag: "🇧🇩" },
    { name: "Berlin", country: "Germany", timezone: "Europe/Berlin", flag: "🇩🇪" },
    { name: "Los Angeles", country: "USA", timezone: "America/Los_Angeles", flag: "🇺🇸" },
    { name: "Chicago", country: "USA", timezone: "America/Chicago", flag: "🇺🇸" },
    { name: "Toronto", country: "Canada", timezone: "America/Toronto", flag: "🇨🇦" },
    { name: "Sao Paulo", country: "Brazil", timezone: "America/Sao_Paulo", flag: "🇧🇷" },
    { name: "Mexico City", country: "Mexico", timezone: "America/Mexico_City", flag: "🇲🇽" },
    { name: "Moscow", country: "Russia", timezone: "Europe/Moscow", flag: "🇷🇺" },
    { name: "Dubai", country: "UAE", timezone: "Asia/Dubai", flag: "🇦🇪" },
    { name: "Mumbai", country: "India", timezone: "Asia/Kolkata", flag: "🇮🇳" },
    { name: "Shanghai", country: "China", timezone: "Asia/Shanghai", flag: "🇨🇳" },
    { name: "Singapore", country: "Singapore", timezone: "Asia/Singapore", flag: "🇸🇬" },
    { name: "Seoul", country: "South Korea", timezone: "Asia/Seoul", flag: "🇰🇷" },
    { name: "Kabul", country: "Afghanistan", timezone: "Asia/Kabul", flag: "🇦🇫" },
    { name: "Mariehamn", country: "Åland Islands", timezone: "Europe/Mariehamn", flag: "🇦🇽" },
    { name: "Tirana", country: "Albania", timezone: "Europe/Tirane", flag: "🇦🇱" },
    { name: "Algiers", country: "Algeria", timezone: "Africa/Algiers", flag: "🇩🇿" },
    { name: "Pago Pago", country: "American Samoa", timezone: "Pacific/Pago_Pago", flag: "🇦🇸" },
    { name: "Andorra la Vella", country: "Andorra", timezone: "Europe/Andorra", flag: "🇦🇩" },
    { name: "Luanda", country: "Angola", timezone: "Africa/Luanda", flag: "🇦🇴" },
    { name: "The Valley", country: "Anguilla", timezone: "America/Anguilla", flag: "🇦🇮" },
    { name: "St. John's", country: "Antigua and Barbuda", timezone: "America/Antigua", flag: "🇦🇬" },
    { name: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires", flag: "🇦🇷" },
    { name: "Yerevan", country: "Armenia", timezone: "Asia/Yerevan", flag: "🇦🇲" },
    { name: "Oranjestad", country: "Aruba", timezone: "America/Aruba", flag: "🇦🇼" },
    { name: "Canberra", country: "Australia", timezone: "Australia/Canberra", flag: "🇦🇺" },
    { name: "Vienna", country: "Austria", timezone: "Europe/Vienna", flag: "🇦🇹" },
    { name: "Baku", country: "Azerbaijan", timezone: "Asia/Baku", flag: "🇦🇿" },
    { name: "Nassau", country: "Bahamas", timezone: "America/Nassau", flag: "🇧🇸" },
    { name: "Manama", country: "Bahrain", timezone: "Asia/Bahrain", flag: "🇧🇭" },
    { name: "Bridgetown", country: "Barbados", timezone: "America/Barbados", flag: "🇧🇧" },
    { name: "Minsk", country: "Belarus", timezone: "Europe/Minsk", flag: "🇧🇾" },
    { name: "Brussels", country: "Belgium", timezone: "Europe/Brussels", flag: "🇧🇪" },
    { name: "Belmopan", country: "Belize", timezone: "America/Belize", flag: "🇧🇿" },
    { name: "Porto-Novo", country: "Benin", timezone: "Africa/Porto-Novo", flag: "🇧🇯" },
    { name: "Hamilton", country: "Bermuda", timezone: "Atlantic/Bermuda", flag: "🇧🇲" },
    { name: "Thimphu", country: "Bhutan", timezone: "Asia/Thimphu", flag: "🇧🇹" },
    { name: "Sucre", country: "Bolivia", timezone: "America/La_Paz", flag: "🇧🇴" },
    { name: "Sarajevo", country: "Bosnia and Herzegovina", timezone: "Europe/Sarajevo", flag: "🇧🇦" },
    { name: "Gaborone", country: "Botswana", timezone: "Africa/Gaborone", flag: "🇧🇼" },
    { name: "Brasília", country: "Brazil", timezone: "America/Sao_Paulo", flag: "🇧🇷" },
    { name: "Road Town", country: "British Virgin Islands", timezone: "America/Tortola", flag: "🇻🇬" },
    { name: "Bandar Seri Begawan", country: "Brunei", timezone: "Asia/Brunei", flag: "🇧🇳" },
    { name: "Sofia", country: "Bulgaria", timezone: "Europe/Sofia", flag: "🇧🇬" },
    { name: "Ouagadougou", country: "Burkina Faso", timezone: "Africa/Ouagadougou", flag: "🇧🇫" },
    { name: "Gitega", country: "Burundi", timezone: "Africa/Bujumbura", flag: "🇧🇮" },
    { name: "Phnom Penh", country: "Cambodia", timezone: "Asia/Phnom_Penh", flag: "🇰🇭" },
    { name: "Yaoundé", country: "Cameroon", timezone: "Africa/Douala", flag: "🇨🇲" },
    { name: "Ottawa", country: "Canada", timezone: "America/Toronto", flag: "🇨🇦" },
    { name: "Praia", country: "Cape Verde", timezone: "Atlantic/Cape_Verde", flag: "🇨🇻" },
    { name: "George Town", country: "Cayman Islands", timezone: "America/Cayman", flag: "🇰🇾" },
    { name: "Bangui", country: "Central African Republic", timezone: "Africa/Bangui", flag: "🇨🇫" },
    { name: "N'Djamena", country: "Chad", timezone: "Africa/Ndjamena", flag: "🇹🇩" },
    { name: "Santiago", country: "Chile", timezone: "America/Santiago", flag: "🇨🇱" },
    { name: "Beijing", country: "China", timezone: "Asia/Shanghai", flag: "🇨🇳" },
    { name: "Flying Fish Cove", country: "Christmas Island", timezone: "Indian/Christmas", flag: "🇨🇽" },
    { name: "West Island", country: "Cocos (Keeling) Islands", timezone: "Indian/Cocos", flag: "🇨🇨" },
    { name: "Bogotá", country: "Colombia", timezone: "America/Bogota", flag: "🇨🇴" },
    { name: "Moroni", country: "Comoros", timezone: "Indian/Comoro", flag: "🇰🇲" },
    { name: "Brazzaville", country: "Congo", timezone: "Africa/Brazzaville", flag: "🇨🇬" },
    { name: "Avarua", country: "Cook Islands", timezone: "Pacific/Rarotonga", flag: "🇨🇰" },
    { name: "San José", country: "Costa Rica", timezone: "America/Costa_Rica", flag: "🇨🇷" },
    { name: "Zagreb", country: "Croatia", timezone: "Europe/Zagreb", flag: "🇭🇷" },
    { name: "Havana", country: "Cuba", timezone: "America/Havana", flag: "🇨🇺" },
    { name: "Willemstad", country: "Curaçao", timezone: "America/Curacao", flag: "🇨🇼" },
    { name: "Nicosia", country: "Cyprus", timezone: "Asia/Nicosia", flag: "🇨🇾" },
    { name: "Prague", country: "Czech Republic", timezone: "Europe/Prague", flag: "🇨🇿" },
    { name: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen", flag: "🇩🇰" },
    { name: "Djibouti", country: "Djibouti", timezone: "Africa/Djibouti", flag: "🇩🇯" },
    { name: "Roseau", country: "Dominica", timezone: "America/Dominica", flag: "🇩🇲" },
    { name: "Santo Domingo", country: "Dominican Republic", timezone: "America/Santo_Domingo", flag: "🇩🇴" },
    { name: "Kinshasa", country: "DR Congo", timezone: "Africa/Kinshasa", flag: "🇨🇩" },
    { name: "Quito", country: "Ecuador", timezone: "America/Guayaquil", flag: "🇪🇨" },
    { name: "Cairo", country: "Egypt", timezone: "Africa/Cairo", flag: "🇪🇬" },
    { name: "San Salvador", country: "El Salvador", timezone: "America/El_Salvador", flag: "🇸🇻" },
    { name: "Malabo", country: "Equatorial Guinea", timezone: "Africa/Malabo", flag: "🇬🇶" },
    { name: "Asmara", country: "Eritrea", timezone: "Africa/Asmara", flag: "🇪🇷" },
    { name: "Tallinn", country: "Estonia", timezone: "Europe/Tallinn", flag: "🇪🇪" },
    { name: "Mbabane", country: "Eswatini", timezone: "Africa/Mbabane", flag: "🇸🇿" },
    { name: "Addis Ababa", country: "Ethiopia", timezone: "Africa/Addis_Ababa", flag: "🇪🇹" },
    { name: "Stanley", country: "Falkland Islands", timezone: "Atlantic/Stanley", flag: "🇫🇰" },
    { name: "Tórshavn", country: "Faroe Islands", timezone: "Atlantic/Faroe", flag: "🇫🇴" },
    { name: "Suva", country: "Fiji", timezone: "Pacific/Fiji", flag: "🇫🇯" },
    { name: "Helsinki", country: "Finland", timezone: "Europe/Helsinki", flag: "🇫🇮" },
    { name: "Cayenne", country: "French Guiana", timezone: "America/Cayenne", flag: "🇬🇫" },
    { name: "Papeete", country: "French Polynesia", timezone: "Pacific/Tahiti", flag: "🇵🇫" },
    { name: "Libreville", country: "Gabon", timezone: "Africa/Libreville", flag: "🇬🇦" },
    { name: "Banjul", country: "Gambia", timezone: "Africa/Banjul", flag: "🇬🇲" },
    { name: "Tbilisi", country: "Georgia", timezone: "Asia/Tbilisi", flag: "🇬🇪" },
    { name: "Accra", country: "Ghana", timezone: "Africa/Accra", flag: "🇬🇭" },
    { name: "Gibraltar", country: "Gibraltar", timezone: "Europe/Gibraltar", flag: "🇬🇮" },
    { name: "Athens", country: "Greece", timezone: "Europe/Athens", flag: "🇬🇷" },
    { name: "Nuuk", country: "Greenland", timezone: "America/Nuuk", flag: "🇬🇱" },
    { name: "St. George's", country: "Grenada", timezone: "America/Grenada", flag: "🇬🇩" },
    { name: "Basse-Terre", country: "Guadeloupe", timezone: "America/Guadeloupe", flag: "🇬🇵" },
    { name: "Hagåtña", country: "Guam", timezone: "Pacific/Guam", flag: "🇬🇺" },
    { name: "Guatemala City", country: "Guatemala", timezone: "America/Guatemala", flag: "🇬🇹" },
    { name: "St. Peter Port", country: "Guernsey", timezone: "Europe/Guernsey", flag: "🇬🇬" },
    { name: "Conakry", country: "Guinea", timezone: "Africa/Conakry", flag: "🇬🇳" },
    { name: "Bissau", country: "Guinea-Bissau", timezone: "Africa/Bissau", flag: "🇬🇼" },
    { name: "Georgetown", country: "Guyana", timezone: "America/Guyana", flag: "🇬🇾" },
    { name: "Port-au-Prince", country: "Haiti", timezone: "America/Port-au-Prince", flag: "🇭🇹" },
    { name: "Tegucigalpa", country: "Honduras", timezone: "America/Tegucigalpa", flag: "🇭🇳" },
    { name: "Hong Kong", country: "Hong Kong", timezone: "Asia/Hong_Kong", flag: "🇭🇰" },
    { name: "Budapest", country: "Hungary", timezone: "Europe/Budapest", flag: "🇭🇺" },
    { name: "Reykjavik", country: "Iceland", timezone: "Atlantic/Reykjavik", flag: "🇮🇸" },
    { name: "New Delhi", country: "India", timezone: "Asia/Kolkata", flag: "🇮🇳" },
    { name: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta", flag: "🇮🇩" },
    { name: "Tehran", country: "Iran", timezone: "Asia/Tehran", flag: "🇮🇷" },
    { name: "Baghdad", country: "Iraq", timezone: "Asia/Baghdad", flag: "🇮🇶" },
    { name: "Dublin", country: "Ireland", timezone: "Europe/Dublin", flag: "🇮🇪" },
    { name: "Douglas", country: "Isle of Man", timezone: "Europe/Isle_of_Man", flag: "🇮🇲" },
    { name: "Jerusalem", country: "Israel", timezone: "Asia/Jerusalem", flag: "🇮🇱" },
    { name: "Rome", country: "Italy", timezone: "Europe/Rome", flag: "🇮🇹" },
    { name: "Yamoussoukro", country: "Ivory Coast", timezone: "Africa/Abidjan", flag: "🇨🇮" },
    { name: "Kingston", country: "Jamaica", timezone: "America/Jamaica", flag: "🇯🇲" },
    { name: "Saint Helier", country: "Jersey", timezone: "Europe/Jersey", flag: "🇯🇪" },
    { name: "Amman", country: "Jordan", timezone: "Asia/Amman", flag: "🇯🇴" },
    { name: "Nur-Sultan", country: "Kazakhstan", timezone: "Asia/Almaty", flag: "🇰🇿" },
    { name: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi", flag: "🇰🇪" },
    { name: "Tarawa", country: "Kiribati", timezone: "Pacific/Tarawa", flag: "🇰🇮" },
    { name: "Pristina", country: "Kosovo", timezone: "Europe/Belgrade", flag: "🇽🇰" },
    { name: "Kuwait City", country: "Kuwait", timezone: "Asia/Kuwait", flag: "🇰🇼" },
    { name: "Bishkek", country: "Kyrgyzstan", timezone: "Asia/Bishkek", flag: "🇰🇬" },
    { name: "Vientiane", country: "Laos", timezone: "Asia/Vientiane", flag: "🇱🇦" },
    { name: "Riga", country: "Latvia", timezone: "Europe/Riga", flag: "🇱🇻" },
    { name: "Beirut", country: "Lebanon", timezone: "Asia/Beirut", flag: "🇱🇧" },
    { name: "Maseru", country: "Lesotho", timezone: "Africa/Maseru", flag: "🇱🇸" },
    { name: "Monrovia", country: "Liberia", timezone: "Africa/Monrovia", flag: "🇱🇷" },
    { name: "Tripoli", country: "Libya", timezone: "Africa/Tripoli", flag: "🇱🇾" },
    { name: "Vaduz", country: "Liechtenstein", timezone: "Europe/Vaduz", flag: "🇱🇮" },
    { name: "Vilnius", country: "Lithuania", timezone: "Europe/Vilnius", flag: "🇱🇹" },
    { name: "Luxembourg", country: "Luxembourg", timezone: "Europe/Luxembourg", flag: "🇱🇺" },
    { name: "Macau", country: "Macau", timezone: "Asia/Macau", flag: "🇲🇴" },
    { name: "Antananarivo", country: "Madagascar", timezone: "Indian/Antananarivo", flag: "🇲🇬" },
    { name: "Lilongwe", country: "Malawi", timezone: "Africa/Blantyre", flag: "🇲🇼" },
    { name: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur", flag: "🇲🇾" },
    { name: "Malé", country: "Maldives", timezone: "Indian/Maldives", flag: "🇲🇻" },
    { name: "Bamako", country: "Mali", timezone: "Africa/Bamako", flag: "🇲🇱" },
    { name: "Valletta", country: "Malta", timezone: "Europe/Malta", flag: "🇲🇹" },
    { name: "Majuro", country: "Marshall Islands", timezone: "Pacific/Majuro", flag: "🇲🇭" },
    { name: "Fort-de-France", country: "Martinique", timezone: "America/Martinique", flag: "🇲🇶" },
    { name: "Nouakchott", country: "Mauritania", timezone: "Africa/Nouakchott", flag: "🇲🇷" },
    { name: "Port Louis", country: "Mauritius", timezone: "Indian/Mauritius", flag: "🇲🇺" },
    { name: "Mamoudzou", country: "Mayotte", timezone: "Indian/Mayotte", flag: "🇾🇹" },
    { name: "Palikir", country: "Micronesia", timezone: "Pacific/Pohnpei", flag: "🇫🇲" },
    { name: "Chișinău", country: "Moldova", timezone: "Europe/Chisinau", flag: "🇲🇩" },
    { name: "Monaco", country: "Monaco", timezone: "Europe/Monaco", flag: "🇲🇨" },
    { name: "Ulaanbaatar", country: "Mongolia", timezone: "Asia/Ulaanbaatar", flag: "🇲🇳" },
    { name: "Podgorica", country: "Montenegro", timezone: "Europe/Podgorica", flag: "🇲🇪" },
    { name: "Plymouth", country: "Montserrat", timezone: "America/Montserrat", flag: "🇲🇸" },
    { name: "Rabat", country: "Morocco", timezone: "Africa/Casablanca", flag: "🇲🇦" },
    { name: "Maputo", country: "Mozambique", timezone: "Africa/Maputo", flag: "🇲🇿" },
    { name: "Naypyidaw", country: "Myanmar", timezone: "Asia/Yangon", flag: "🇲🇲" },
    { name: "Windhoek", country: "Namibia", timezone: "Africa/Windhoek", flag: "🇳🇦" },
    { name: "Yaren", country: "Nauru", timezone: "Pacific/Nauru", flag: "🇳🇷" },
    { name: "Kathmandu", country: "Nepal", timezone: "Asia/Kathmandu", flag: "🇳🇵" },
    { name: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam", flag: "🇳🇱" },
    { name: "Nouméa", country: "New Caledonia", timezone: "Pacific/Noumea", flag: "🇳🇨" },
    { name: "Wellington", country: "New Zealand", timezone: "Pacific/Auckland", flag: "🇳🇿" },
    { name: "Managua", country: "Nicaragua", timezone: "America/Managua", flag: "🇳🇮" },
    { name: "Niamey", country: "Niger", timezone: "Africa/Niamey", flag: "🇳🇪" },
    { name: "Abuja", country: "Nigeria", timezone: "Africa/Lagos", flag: "🇳🇬" },
    { name: "Alofi", country: "Niue", timezone: "Pacific/Niue", flag: "🇳🇺" },
    { name: "Kingston", country: "Norfolk Island", timezone: "Pacific/Norfolk", flag: "🇳🇫" },
    { name: "Pyongyang", country: "North Korea", timezone: "Asia/Pyongyang", flag: "🇰🇵" },
    { name: "Skopje", country: "North Macedonia", timezone: "Europe/Skopje", flag: "🇲🇰" },
    { name: "Saipan", country: "Northern Mariana Islands", timezone: "Pacific/Saipan", flag: "🇲🇵" },
    { name: "Oslo", country: "Norway", timezone: "Europe/Oslo", flag: "🇳🇴" },
    { name: "Muscat", country: "Oman", timezone: "Asia/Muscat", flag: "🇴🇲" },
    { name: "Islamabad", country: "Pakistan", timezone: "Asia/Karachi", flag: "🇵🇰" },
    { name: "Ngerulmud", country: "Palau", timezone: "Pacific/Palau", flag: "🇵🇼" },
    { name: "Ramallah", country: "Palestine", timezone: "Asia/Gaza", flag: "🇵🇸" },
    { name: "Panama City", country: "Panama", timezone: "America/Panama", flag: "🇵🇦" },
    { name: "Port Moresby", country: "Papua New Guinea", timezone: "Pacific/Port_Moresby", flag: "🇵🇬" },
    { name: "Asunción", country: "Paraguay", timezone: "America/Asuncion", flag: "🇵🇾" },
    { name: "Lima", country: "Peru", timezone: "America/Lima", flag: "🇵🇪" },
    { name: "Manila", country: "Philippines", timezone: "Asia/Manila", flag: "🇵🇭" },
    { name: "Adamstown", country: "Pitcairn Islands", timezone: "Pacific/Pitcairn", flag: "🇵🇳" },
    { name: "Warsaw", country: "Poland", timezone: "Europe/Warsaw", flag: "🇵🇱" },
    { name: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon", flag: "🇵🇹" },
    { name: "San Juan", country: "Puerto Rico", timezone: "America/Puerto_Rico", flag: "🇵🇷" },
    { name: "Doha", country: "Qatar", timezone: "Asia/Qatar", flag: "🇶🇦" },
    { name: "Saint-Denis", country: "Réunion", timezone: "Indian/Reunion", flag: "🇷🇪" },
    { name: "Bucharest", country: "Romania", timezone: "Europe/Bucharest", flag: "🇷🇴" },
    { name: "Kigali", country: "Rwanda", timezone: "Africa/Kigali", flag: "🇷🇼" },
    { name: "Gustavia", country: "Saint Barthélemy", timezone: "America/St_Barthelemy", flag: "🇧🇱" },
    { name: "Jamestown", country: "Saint Helena", timezone: "Atlantic/St_Helena", flag: "🇸🇭" },
    { name: "Basseterre", country: "Saint Kitts and Nevis", timezone: "America/St_Kitts", flag: "🇰🇳" },
    { name: "Castries", country: "Saint Lucia", timezone: "America/St_Lucia", flag: "🇱🇨" },
    { name: "Marigot", country: "Saint Martin", timezone: "America/Marigot", flag: "🇲🇫" },
    { name: "Saint-Pierre", country: "Saint Pierre and Miquelon", timezone: "America/Miquelon", flag: "🇵🇲" },
    { name: "Kingstown", country: "Saint Vincent and the Grenadines", timezone: "America/St_Vincent", flag: "🇻🇨" },
    { name: "Apia", country: "Samoa", timezone: "Pacific/Apia", flag: "🇼🇸" },
    { name: "San Marino", country: "San Marino", timezone: "Europe/San_Marino", flag: "🇸🇲" },
    { name: "São Tomé", country: "São Tomé and Príncipe", timezone: "Africa/Sao_Tome", flag: "🇸🇹" },
    { name: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh", flag: "🇸🇦" },
    { name: "Dakar", country: "Senegal", timezone: "Africa/Dakar", flag: "🇸🇳" },
    { name: "Belgrade", country: "Serbia", timezone: "Europe/Belgrade", flag: "🇷🇸" },
    { name: "Victoria", country: "Seychelles", timezone: "Indian/Mahe", flag: "🇸🇨" },
    { name: "Freetown", country: "Sierra Leone", timezone: "Africa/Freetown", flag: "🇸🇱" },
    { name: "Philipsburg", country: "Sint Maarten", timezone: "America/Lower_Princes", flag: "🇸🇽" },
    { name: "Bratislava", country: "Slovakia", timezone: "Europe/Bratislava", flag: "🇸🇰" },
    { name: "Ljubljana", country: "Slovenia", timezone: "Europe/Ljubljana", flag: "🇸🇮" },
    { name: "Honiara", country: "Solomon Islands", timezone: "Pacific/Guadalcanal", flag: "🇸🇧" },
    { name: "Mogadishu", country: "Somalia", timezone: "Africa/Mogadishu", flag: "🇸🇴" },
    { name: "Pretoria", country: "South Africa", timezone: "Africa/Johannesburg", flag: "🇿🇦" },
    { name: "Juba", country: "South Sudan", timezone: "Africa/Juba", flag: "🇸🇸" },
    { name: "Madrid", country: "Spain", timezone: "Europe/Madrid", flag: "🇪🇸" },
    { name: "Sri Jayawardenepura Kotte", country: "Sri Lanka", timezone: "Asia/Colombo", flag: "🇱🇰" },
    { name: "Khartoum", country: "Sudan", timezone: "Africa/Khartoum", flag: "🇸🇩" },
    { name: "Paramaribo", country: "Suriname", timezone: "America/Paramaribo", flag: "🇸🇷" },
    { name: "Longyearbyen", country: "Svalbard and Jan Mayen", timezone: "Arctic/Longyearbyen", flag: "🇸🇯" },
    { name: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm", flag: "🇸🇪" },
    { name: "Bern", country: "Switzerland", timezone: "Europe/Zurich", flag: "🇨🇭" },
    { name: "Damascus", country: "Syria", timezone: "Asia/Damascus", flag: "🇸🇾" },
    { name: "Taipei", country: "Taiwan", timezone: "Asia/Taipei", flag: "🇹🇼" },
    { name: "Dushanbe", country: "Tajikistan", timezone: "Asia/Dushanbe", flag: "🇹🇯" },
    { name: "Dodoma", country: "Tanzania", timezone: "Africa/Dar_es_Salaam", flag: "🇹🇿" },
    { name: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok", flag: "🇹🇭" },
    { name: "Dili", country: "Timor-Leste", timezone: "Asia/Dili", flag: "🇹🇱" },
    { name: "Lomé", country: "Togo", timezone: "Africa/Lome", flag: "🇹🇬" },
    { name: "Fakaofo", country: "Tokelau", timezone: "Pacific/Fakaofo", flag: "🇹🇰" },
    { name: "Nuku'alofa", country: "Tonga", timezone: "Pacific/Tongatapu", flag: "🇹🇴" },
    { name: "Port of Spain", country: "Trinidad and Tobago", timezone: "America/Port_of_Spain", flag: "🇹🇹" },
    { name: "Tunis", country: "Tunisia", timezone: "Africa/Tunis", flag: "🇹🇳" },
    { name: "Ankara", country: "Turkey", timezone: "Europe/Istanbul", flag: "🇹🇷" },
    { name: "Ashgabat", country: "Turkmenistan", timezone: "Asia/Ashgabat", flag: "🇹🇲" },
    { name: "Cockburn Town", country: "Turks and Caicos Islands", timezone: "America/Grand_Turk", flag: "🇹🇨" },
    { name: "Funafuti", country: "Tuvalu", timezone: "Pacific/Funafuti", flag: "🇹🇻" },
    { name: "Kampala", country: "Uganda", timezone: "Africa/Kampala", flag: "🇺🇬" },
    { name: "Kyiv", country: "Ukraine", timezone: "Europe/Kiev", flag: "🇺🇦" },
    { name: "Abu Dhabi", country: "United Arab Emirates", timezone: "Asia/Dubai", flag: "🇦🇪" },
    { name: "Washington, D.C.", country: "United States", timezone: "America/New_York", flag: "🇺🇸" },
    { name: "Montevideo", country: "Uruguay", timezone: "America/Montevideo", flag: "🇺🇾" },
    { name: "Tashkent", country: "Uzbekistan", timezone: "Asia/Tashkent", flag: "🇺🇿" },
    { name: "Port Vila", country: "Vanuatu", timezone: "Pacific/Efate", flag: "🇻🇺" },
    { name: "Vatican City", country: "Vatican City", timezone: "Europe/Vatican", flag: "🇻🇦" },
    { name: "Caracas", country: "Venezuela", timezone: "America/Caracas", flag: "🇻🇪" },
    { name: "Hanoi", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", flag: "🇻🇳" },
    { name: "Mata-Utu", country: "Wallis and Futuna", timezone: "Pacific/Wallis", flag: "🇼🇫" },
    { name: "El Aaiún", country: "Western Sahara", timezone: "Africa/El_Aaiun", flag: "🇪🇭" },
    { name: "Sana'a", country: "Yemen", timezone: "Asia/Aden", flag: "🇾🇪" },
    { name: "Lusaka", country: "Zambia", timezone: "Africa/Lusaka", flag: "🇿🇲" },
    { name: "Harare", country: "Zimbabwe", timezone: "Africa/Harare", flag: "🇿🇼" },
];

// A list of popular cities for quick selection. The 'size' property can be used for styling, e.g., font size.
export const POPULAR_CITIES = [
    { name: "Abu Dhabi", size: 2, timezone: "Asia/Dubai" }, { name: "Dhaka", size: 3, timezone: "Asia/Dhaka" },
    { name: "Beijing", size: 5, timezone: "Asia/Shanghai" }, { name: "Berlin", size: 3, timezone: "Europe/Berlin" },
    { name: "Buenos Aires", size: 4, timezone: "America/Argentina/Buenos_Aires" }, { name: "Cairo", size: 3, timezone: "Africa/Cairo" }, { name: "Chicago", size: 4, timezone: "America/Chicago" }, { name: "Delhi", size: 5, timezone: "Asia/Kolkata" },
    { name: "Dubai", size: 4, timezone: "Asia/Dubai" }, { name: "Istanbul", size: 5, timezone: "Europe/Istanbul" }, 
    { name: "London", size: 5, timezone: "Europe/London" }, { name: "Los Angeles", size: 5, timezone: "America/Los_Angeles" },
    { name: "Mexico City", size: 5, timezone: "America/Mexico_City" }, { name: "Moscow", size: 4, timezone: "Europe/Moscow" }, { name: "Mumbai", size: 4, timezone: "Asia/Kolkata" },
    { name: "New York", size: 5, timezone: "America/New_York" }, { name: "Paris", size: 4, timezone: "Europe/Paris" }, 
    { name: "Seoul", size: 4, timezone: "Asia/Seoul" }, { name: "Shanghai", size: 4, timezone: "Asia/Shanghai" }, { name: "Sydney", size: 4, timezone: "Australia/Sydney" }, { name: "São Paulo", size: 5, timezone: "America/Sao_Paulo" },
    { name: "Tokyo", size: 5, timezone: "Asia/Tokyo" },
];

// Translation strings for supporting multiple languages in the UI.
export const TRANSLATIONS: Record<string, any> = {
    en: { name: "English", ui: { notes: "Notes for", calendar: "Calendar", settings: "Settings", theme: "Theme", autoTheme: "Auto Theme", darkMode: "Dark Mode", format: "Format", hourFormat: "24-Hour Format", language: "Language", reset: "Reset All Data", allNotes: "All Notes", showAllNotes: "Show All Notes", noNotes: "No notes found.", refresh: "Refresh Cards" }, placeholders: { search: "Search for a city or country...", notes: "Write something for the selected date...", alarmLabel: "Alarm label" }, alerts: { resetClocksConfirm: "This will remove all pinned clocks. Are you sure?", resetNotesAlarmsConfirm: "Do you also want to remove all notes and alarms?", noPinned: "Search for a city to pin a clock." }, time: { ahead: "ahead", behind: "behind", same: "Same time", hour: "hour", hours: "hours" }, calendar: { months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] } },
    bn: { name: "বাংলা (Bangla)", ui: { notes: "নোট", calendar: "ক্যালেন্ডার", settings: "সেটিংস", theme: "থিম", autoTheme: "স্বয়ংক্রিয় থিম", darkMode: "ডার্ক মোড", format: "ফরম্যাট", hourFormat: "২৪-ঘন্টা ফরম্যাট", language: "ভাষা", reset: "সব ডেটা রিসেট করুন", allNotes: "সমস্ত নোট", showAllNotes: "সব নোট দেখুন", noNotes: "কোন নোট পাওয়া যায়নি।", refresh: "কার্ড রিফ্রেশ করুন" }, placeholders: { search: "শহর বা দেশ খুঁজুন...", notes: "কিছু লিখুন...", alarmLabel: "অ্যালার্ম লেবেল" }, alerts: { resetClocksConfirm: "এটি সমস্ত পিন করা ঘড়ি মুছে ফেলবে। আপনি কি নিশ্চিত?", resetNotesAlarmsConfirm: "আপনি কি সমস্ত নোট এবং অ্যালার্মও মুছে ফেলতে চান?", noPinned: "ঘড়ি পিন করতে একটি শহর অনুসন্ধান করুন।" }, time: { ahead: "এগিয়ে", behind: "পিছিয়ে", same: "একই সময়", hour: "ঘন্টা", hours: "ঘন্টা" }, calendar: { months: ["জানুয়ারী", "ফেব্রুয়ারী", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্টেম্বর", "অক্টোবর", "নভেম্বর", "ডিসেম্বর"], weekdays: ["রবি", "সোম", "মঙ্গল", "বুধ", "বৃহঃ", "শুক্র", "শনি"] } },
    es: { name: "Español", ui: { notes: "Notas para", calendar: "Calendario", settings: "Ajustes", theme: "Tema", autoTheme: "Tema automático", darkMode: "Modo oscuro", format: "Formato", hourFormat: "Formato 24 horas", language: "Idioma", reset: "Restablecer datos", allNotes: "Todas las notas", showAllNotes: "Mostrar todas las notas", noNotes: "No se encontraron notas.", refresh: "Actualizar tarjetas" }, placeholders: { search: "Buscar una ciudad o país...", notes: "Escribe algo...", alarmLabel: "Etiqueta de alarma" }, alerts: { resetClocksConfirm: "¿Estás seguro? Esto eliminará todos los relojes fijados.", resetNotesAlarmsConfirm: "¿Deseas eliminar también todas las notas y alarmas?", noPinned: "Busca una ciudad para fijar un reloj." }, time: { ahead: "adelantado", behind: "atrasado", same: "Misma hora", hour: "hora", hours: "horas" }, calendar: { months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"], weekdays: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"] } }
};